### ISSUE TITLE
Include "sequences to avoid" option

### ISSUE THREAD

**Issue by eggrandio** [JBEI/basebuddy#1]
Hello,

It would be good if, in addition to poly-nts and restriction sites, custom sequences could be included to be avoided implementing `AvoidPattern` from DNAchisel.
For example, for protein expression in plants (https://pubmed.ncbi.nlm.nih.gov/24854834/), some sequences such as ATTTA or MAGGTRAGT can have detrimental effects.

Thank you for developing such an useful tool ! :)

**Comment by mschmidt75** [comment]
Hi eggrandio,

Thanks a lot for your input! :) And sorry that it took so long.

We have added the requested function to the advanced settings. However, only DNA sequence patterns can be avoided. I am not sure how to realize an "avoid peptide sequence" function?

**Comment by eggrandio** [comment]
Thank you for adding it! This works perfectly.

I apologize for the confusion, in the MAGGTRAGT sequence, M and R are "wobble" nucleotides (M stands for A or C).

**Comment by mschmidt75** [comment]
Gotcha! You should be able to add all possible combinations for the MAGGTRAGT sequence into the Avoid custom patterns box.

Glad it works :) Please let me know if you run into any other issues.
